### ISSUE TITLE
how to train on custom dataset?

### ISSUE THREAD

**Issue by sontung** [gtolias/how#10]
Hi,
I would like to ask how to prepare a custom dataset to train the descriptor on? I want to finetune the network on my custom SfM dataset. Thanks.

**Comment by jenicek** [comment]
Hi, the dataset is initialized in https://github.com/gtolias/how/blob/7c2d6ebbb6cb8d53f31834c27bc3fa217c11d62e/how/stages/train.py#L132 if you want to use a custom implementation of `torch.utils.data.Dataset`. Alternatively, you can modify directly the cirtorch implementation https://github.com/filipradenovic/cnnimageretrieval-pytorch/blob/master/cirtorch/datasets/traindataset.py . The parameters from the yaml config file https://github.com/gtolias/how/blob/7c2d6ebbb6cb8d53f31834c27bc3fa217c11d62e/examples/params/eccv20/_train_how.yml#L24-L30 are passed directly to the initializer.

**Comment by sontung** [comment]
Thanks for the reply, how can I structure the dataset in the same way as "retrieval-SfM-120k"? By the way, do you know if the positive pairs of this dataset were clustered based on the whole 7-dof poses or just the 3-dof positions?

**Comment by jenicek** [comment]
You can start with the linked cirtorch dataset https://github.com/filipradenovic/cnnimageretrieval-pytorch/blob/master/cirtorch/datasets/traindataset.py . For questions about the ground-truth files from the cirtorch project, please refer to the corresponding repository https://github.com/filipradenovic/cnnimageretrieval-pytorch .
