### ISSUE TITLE
about the local features

### ISSUE THREAD

**Issue by KN-Zhang** [gtolias/how#11]
Hello~ I read the codes and found that local features are selected based on the feature maps which have smaller resolution than that of the input images. But in the paper, Fig.3 illustrates local features on the original images. So how does that work? First rescaling the feature map as well as the heatmap and then selecting features?

**Comment by gtolias** [comment]
Selection is performed on the feature maps. Then, the heat-maps, and therefore the local features, are resized to the size of the original image for the visualization only.
