### ISSUE TITLE
Storing an asmk.asmk_method.ASMKMethod

### ISSUE THREAD

**Issue by mdouze** [gtolias/how#5]
Hi!

I am running HOW on a relatively large dataset and I would like to store the index into a file after it is built (and of course reload it). 
is there a way of doing this? 

Thanks!

**Comment by jenicek** [comment]
Hi, asmk index saving and loading is not exposed in the how package. When using `ASMKMethod` from the [asmk package](https://github.com/jenicek/asmk), you can use parameter `cache_path` of the `build_ivf` method to save and load the index automatically. If this does not suit you, you can have a look at how saving and loading is handled in the `build_ivf` method and open an issue in the asmk package if needed.
