### ISSUE TITLE
speed up query_ivf 

### ISSUE THREAD

**Issue by zjhthu** [gtolias/how#8]
I find `query_ivf` takes more time than extracting local features. For example, extracting features takes 14ms while `query_ivf` takes 66ms when searching in 3000 database images. 
So how to speed up the searching process. Is it possible to move this to gpu? I find the local features are moved to cpu before  `query_ivf`. Does ASMK support GPU?

**Comment by jenicek** [comment]
Thanks for the feedback. ASMK supports GPU only for quantization (nearest neighbor search using faiss), but not for aggregation or inverted file search. GPU implementation is not straightforward there, but it should be easy to parallelize the code to utilize multiple CPUs as each image and word is processed independently.

**Comment by zjhthu** [comment]
I am trying to parallelize the [aggregation part](https://github.com/jenicek/asmk/blob/master/asmk/kernel.py#L31) but it turns even slower, which are 0.02s vs 1.2s. This might because that every single step takes very little time, and multi-thread has no advantage  in this situation.

```
        from joblib import Parallel, delayed
        import time
        t1 = time.time()
        #'''
        if self.params["binary"]:
            # Storage for packed booleans
            ades = np.empty((unique_ids.shape[0], int(np.ceil(des.shape[1] / 32))), dtype=np.uint32)
        else:
            ades = np.empty((unique_ids.shape[0], des.shape[1]), dtype=np.float32)
        for i, word in enumerate(unique_ids):
            residuals = des[word_ids==word] - self.codebook.centroids[word]
            residual = residuals.sum(0)

            if self.params["binary"]:
                ades[i] = hamming.binarize_and_pack(residual.astype(np.float32))
            else:
                ades[i] = normalize_vec_l2(np.expand_dims(residual, axis=0)).squeeze()
        t1 = time.time() - t1
        #'''
        def fun(word, centroids, params):
            residuals = des[word_ids==word] - centroids[word]
            residual = residuals.sum(0)

            if params["binary"]:
                res = hamming.binarize_and_pack(residual.astype(np.float32))
            else:
                res = normalize_vec_l2(np.expand_dims(residual, axis=0)).squeeze()
            return res
        t2 = time.time()
        ades2 = Parallel(n_jobs=4)(delayed(fun)(word, self.codebook.centroids, self.params) for word in unique_ids)
        t2 = time.time() - t2
```

**Comment by jenicek** [comment]
In this case, you would need to parallelize on the level of images. I would also group the images by e.g. 10, otherwise, I would still expect the process synchronization to dominate the time.
