### ISSUE TITLE
how to detect image？Which py file to use to detect the iamge？

### ISSUE THREAD

**Issue by joeyw1030** [gtolias/how#9]

**Comment by jenicek** [comment]
What do you mean by image detection?

**Comment by joeyw1030** [comment]
Which function is the input image for feature matching ？

**Comment by jenicek** [comment]
If you are interested in the torch Dataset that we use (reading images from the disk), please refer to the [cirtorch package](https://github.com/filipradenovic/cnnimageretrieval-pytorch/)

**Comment by a602759683** [comment]
How to testing the trained model？thanks

**Comment by joeyw1030** [comment]
How to test the trained model？thanks
